import { test, expect } from "@playwright/test";
import { mkdirSync } from "node:fs";

/**
 * README hero screenshots — `screenshots/readme/{dark,light}.jpg`
 *
 * Two 1280×720 hero images of the app with the Info panel open over the map.
 * Dark uses the project-default scheme;
 * light emulates the OS/browser `prefers-color-scheme` preference (the app has
 * no in-app toggle) and asserts the root theme attribute flips to light.
 *
 * Each hero is captured from a genuine cold start: no stored view, and a
 * `?country=random` query that forces the app's random-country fit on every
 * load (the earlier `zxx` locale override is no longer needed — the query
 * outranks timezone and locale). The fitted country is genuinely random on
 * every regeneration; the two themes may land on different countries, and
 * that is expected.
 *
 * These JPEGs are COMMITTED ARTEFACTS — the canonical visual evidence that
 * ships with the repository — generated by local full E2E runs (CI excludes
 * `@screenshots`; see `docs/11.ci.md`). They are not pixel-diff baselines.
 */

test.setTimeout(120000);

const OUT_DIR = "screenshots/readme";

/**
 * Capture the hero composition: cold-start the app on a random country, wait
 * for the map to settle and the Info panel to slide in, assert the resolved
 * theme, snapshot.
 */
const captureHero = async (page, name, theme) => {
  // A genuine cold start: `?country=random` forces a true-random country fit
  // (outranking timezone and locale), regenerated on each run. The app persists
  // the fitted view to the URL hash (and storage) via its `moveend` handler, so
  // a `#map=` hash appearing is the settle signal.
  await page.goto("/?country=random");

  await expect.poll(() => page.url(), { timeout: 30000 }).toContain("#map=");

  await expect(page.locator(".ogis-map")).toHaveAttribute(
    "data-map-idle",
    "true",
    { timeout: 30000 },
  );
  await page.locator(".ogis-panel").waitFor({ state: "visible" });
  await expect(page.locator("html")).toHaveAttribute("data-bs-theme", theme);
  // Let the offcanvas slide-in finish so the hero is not mid-transition.
  await page.waitForTimeout(400);

  console.log(`[README hero ${name}] captured ${page.url()}`);

  await page.screenshot({
    path: `${OUT_DIR}/${name}.jpg`,
    type: "jpeg",
    quality: 80,
  });
};

test.beforeAll(() => {
  mkdirSync(OUT_DIR, { recursive: true });
});

test.describe("README hero — dark", () => {
  test.use({ viewport: { width: 1280, height: 720 } });

  test("README hero dark @screenshots", async ({ page }) => {
    await captureHero(page, "dark", "dark");
  });
});

test.describe("README hero — light", () => {
  test.use({ viewport: { width: 1280, height: 720 }, colorScheme: "light" });

  test("README hero light @screenshots", async ({ page }) => {
    await captureHero(page, "light", "light");
  });
});
