import { test, expect } from "@playwright/test";
import { mkdirSync } from "node:fs";

/**
 * README hero screenshots — `screenshots/readme/{dark,light}.jpg`
 *
 * Two 1280×720 hero images of the app after the welcome modal is dismissed,
 * with the Info panel open over the map. Dark uses the project-default scheme;
 * light emulates the OS/browser `prefers-color-scheme` preference (the app has
 * no in-app toggle) and asserts the root theme attribute flips to light.
 *
 * These JPEGs are COMMITTED CI ARTEFACTS — the canonical visual evidence that
 * ships with the repository — generated by the CI screenshot job and
 * regenerable locally. They are not pixel-diff baselines.
 */

test.setTimeout(120000);

const OUT_DIR = "screenshots/readme";

// Standard test view — Holberg area, BC. z16 keeps the Esri/Mapterhorn
// raster sources on real imagery (z18 falls back to placeholder tiles here).
const TEST_HASH = "#map=16/50.653900/-128.009400";

/** Fresh view storage so the first-load welcome modal appears. */
const withFreshView = (page) =>
  page.addInitScript(() => localStorage.removeItem("ogis_view_app"));

/**
 * Capture the hero composition: dismiss the welcome modal, wait for the map to
 * settle and the Info panel to slide in, assert the resolved theme, snapshot.
 */
const captureHero = async (page, name, theme) => {
  await withFreshView(page);
  await page.goto(`/${TEST_HASH}`);

  const modal = page.locator("#about-modal");
  await modal.waitFor({ state: "visible" });
  await page.locator("#about-modal-close").click();
  await modal.waitFor({ state: "hidden" });

  await expect(page.locator(".ogis-map")).toHaveAttribute(
    "data-map-idle",
    "true",
    { timeout: 30000 },
  );
  await page.locator(".ogis-panel").waitFor({ state: "visible" });
  await expect(page.locator("html")).toHaveAttribute("data-bs-theme", theme);
  // Let the offcanvas slide-in finish so the hero is not mid-transition.
  await page.waitForTimeout(400);

  await page.screenshot({
    path: `${OUT_DIR}/${name}.jpg`,
    type: "jpeg",
    quality: 80,
  });
};

test.beforeAll(() => {
  mkdirSync(OUT_DIR, { recursive: true });
});

test.describe("README hero — dark", () => {
  test.use({ viewport: { width: 1280, height: 720 } });

  test("README hero dark @screenshots", async ({ page }) => {
    await captureHero(page, "dark", "dark");
  });
});

test.describe("README hero — light", () => {
  test.use({ viewport: { width: 1280, height: 720 }, colorScheme: "light" });

  test("README hero light @screenshots", async ({ page }) => {
    await captureHero(page, "light", "light");
  });
});
