import { test, expect } from "@playwright/test";
import { waitForMapIdle } from "../helpers/mapIdle.js";

/**
 * README hero screenshots — `./DARK.jpg` and `./LIGHT.jpg` (repo root).
 *
 * Two 1280×720 hero images of the app with the Info panel open over a live map.
 * Dark uses the project-default scheme; light emulates the OS/browser
 * `prefers-color-scheme` preference (the app has no in-app toggle) and asserts
 * the root theme attribute flips to light.
 *
 * These heroes are DELIBERATELY NON-DETERMINISTIC: each is a genuine cold start
 * against `?country=random`, which fits the view to a different country every
 * run and renders live (un-stubbed) map tiles. That is the whole point — they
 * are marketing imagery showing the real app over real places, not pixel
 * baselines.
 *
 * Consequently this spec must NOT import the shared E2E test fixture
 * (`../helpers/test.js`): that fixture installs the committed map-asset stubs,
 * which would pin the view to the demo area and defeat the random cold start.
 * It uses Playwright's base test directly.
 *
 * The files are COMMITTED ARTEFACTS regenerated by local full E2E runs (CI
 * excludes `@screenshots`; see `docs/13.ci.md`).
 */

test.setTimeout(120000);

// Live tiles: a stalled external request can delay map-idle past the wait.
test.describe.configure({ retries: 1 });

// Random-country cold start. The app's `?country=random` sentinel picks a
// random country and outranks any stored view, so the hero is different every
// run by design.
const HERO_URL = "/?country=random";

/**
 * Capture the hero composition: cold-start the app on a random country, wait
 * for the live map to settle and the Info panel to slide in, assert the
 * resolved theme, snapshot to the repo root.
 */
const captureHero = async (page, testInfo, name, theme) => {
  await page.goto(HERO_URL);

  await waitForMapIdle(page, testInfo);
  await page.locator(".ogis-panel").waitFor({ state: "visible" });
  await expect(page.locator("html")).toHaveAttribute("data-bs-theme", theme);
  // Let the offcanvas slide-in finish so the hero is not mid-transition.
  await page.waitForTimeout(400);

  console.log(`[README hero ${name}] captured ${page.url()}`);

  await page.screenshot({
    path: `${name.toUpperCase()}.jpg`,
    type: "jpeg",
    quality: 80,
  });
};

test.describe("README hero — dark", () => {
  test.use({ viewport: { width: 1280, height: 720 } });

  test("README hero dark @screenshots", async ({ page }, testInfo) => {
    await captureHero(page, testInfo, "dark", "dark");
  });
});

test.describe("README hero — light", () => {
  test.use({ viewport: { width: 1280, height: 720 }, colorScheme: "light" });

  test("README hero light @screenshots", async ({ page }, testInfo) => {
    await captureHero(page, testInfo, "light", "light");
  });
});
