import { test, expect } from "../helpers/test.js";
import {
  trackConsoleErrors,
  expectNoConsoleErrors,
} from "../helpers/console.js";
import { mkdirSync } from "node:fs";

/**
 * UI-states screenshot matrix — `screenshots/{device}/{orientation}/*.jpg`
 *
 * Generates the committed visual-evidence matrix: every core chrome state at
 * six viewport combinations (phone/tablet/desktop × portrait/landscape), all in
 * the project-default dark theme, plus four feature states at the desktop
 * landscape viewport.
 *
 * These JPEGs are COMMITTED ARTEFACTS — the canonical visual evidence that
 * ships with the repository — generated by local full E2E runs (CI excludes
 * `@screenshots`; see `docs/11.ci.md`). Live map tiles make pixel comparisons brittle, so this
 * spec deliberately snapshots rather than compares (an explicit project
 * decision).
 *
 * Dark is the project default (`colorScheme: "dark"` in playwright.config.js).
 * Light mode is covered by the README hero spec and the settings spec.
 *
 * Every capture asserts zero console.error/pageerror. External Mapterhorn
 * raster 404s are filtered as expected network noise (see trackConsoleErrors).
 *
 * Layout note: widths ≥ 992 render the desktop layout (Bootstrap offcanvas
 * breakpoint). The desktop portrait window is a narrow 720 px, so it renders
 * the mobile layout; tablet landscape (1180) and desktop landscape (1280)
 * render the desktop layout.
 */

// SwiftShader software rendering starves the renderer: map-idle waits, drags
// and screenshots can each take tens of seconds. A single test loops all
// states for one viewport, so the default 30 s budget is far too small.
test.setTimeout(300000);

const OUT_ROOT = "screenshots";

// 3-segment hash is accepted and rewritten to 5 on load. z16 keeps the
// Esri/Mapterhorn raster sources on real imagery (z18 shows placeholder tiles).
const BASE_HASH = "#map=16/50.653900/-128.009400";

// Feature states are captured at the desktop landscape viewport only.
const FEATURE_DIR = `${OUT_ROOT}/desktop/landscape`;

// device → orientation → viewport (width × height).
const VIEWPORTS = [
  {
    device: "phone",
    orientation: "portrait",
    width: 390,
    height: 844,
    hasTouch: true,
  },
  {
    device: "phone",
    orientation: "landscape",
    width: 844,
    height: 390,
    hasTouch: true,
  },
  {
    device: "tablet",
    orientation: "portrait",
    width: 820,
    height: 1180,
    hasTouch: true,
  },
  {
    device: "tablet",
    orientation: "landscape",
    width: 1180,
    height: 820,
    hasTouch: true,
  },
  {
    device: "desktop",
    orientation: "portrait",
    width: 720,
    height: 1280,
    hasTouch: false,
  },
  {
    device: "desktop",
    orientation: "landscape",
    width: 1280,
    height: 720,
    hasTouch: false,
  },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Screenshot one state, then assert the capture produced no console errors. */
const capture = async (page, dir, name) => {
  await page.screenshot({
    path: `${dir}/${name}.jpg`,
    type: "jpeg",
    quality: 80,
  });
  expectNoConsoleErrors(page);
};

/** Wait for MapLibre to finish rendering tiles (generous under SwiftShader). */
const waitForMapIdle = (page) =>
  expect(page.locator(".ogis-map")).toHaveAttribute("data-map-idle", "true", {
    timeout: 30000,
  });

/**
 * Seed only the locate permission — the view storage is deliberately left
 * absent so the capture starts from the app's default view. This lets one page
 * load cover the locate/record states without a mid-test reload.
 */
const seedLocatePermission = (page) =>
  page.addInitScript(() => {
    localStorage.setItem(
      "ogis_locate_app",
      JSON.stringify({ permissionGranted: true }),
    );
  });

/** Seed permission + a known view storage. */
const withGrantedStorage = (page) =>
  page.addInitScript(() => {
    localStorage.setItem(
      "ogis_locate_app",
      JSON.stringify({ permissionGranted: true }),
    );
    localStorage.setItem(
      "ogis_view_app",
      JSON.stringify({
        mapView: { center: { lat: 50.6539, lng: -128.0094 }, zoom: 14 },
      }),
    );
  });

/** Grant geolocation permission and set a fixed position. */
const grantGeolocation = (page) =>
  page
    .context()
    .grantPermissions(["geolocation"])
    .then(() =>
      page.context().setGeolocation({
        latitude: 50.6539,
        longitude: -128.0094,
      }),
    );

/** Mouse-drag the map canvas horizontally to collapse the attribution chip. */
const dragMap = async (page, dx = 200) => {
  const canvas = page.locator(".ogis-map canvas");
  await canvas.waitFor({ state: "visible" });
  const box = await canvas.boundingBox();
  const x = box.x + box.width / 2;
  const y = box.y + box.height / 2;
  await page.mouse.move(x, y);
  await page.mouse.down();
  await page.mouse.move(x + dx, y, { steps: 10 });
  await page.mouse.up();
};

/** True when the side panel currently has the Bootstrap `show` class. */
const isPanelShown = (page) =>
  page
    .locator(".ogis-panel.show")
    .count()
    .then((n) => n > 0);

/**
 * Close any open pane. On narrow screens the panel is capped narrower than the
 * viewport, leaving a strip of dismiss backdrop beside it; wait for the
 * slide-in transition to settle, then click that strip with a real pointer
 * event. On desktop there is no backdrop and the panel leaves the controls
 * accessible, so the chip/menu buttons toggle their panes closed.
 */
const closePanel = async (page) => {
  if (!(await isPanelShown(page))) return;
  const backdrop = page.locator(".offcanvas-backdrop");
  if (await backdrop.count()) {
    // The panel no longer covers the backdrop, so a real pointer click on the
    // visible strip reaches the backdrop's Vue close handler. Wait for the
    // offcanvas transform transition first — a mid-slide bounding box would
    // move the click target under the panel.
    await page.waitForFunction(() => {
      const panel = document.querySelector(".ogis-panel");
      return panel && getComputedStyle(panel).transform === "none";
    });
    const panelBox = await page.locator(".ogis-panel").boundingBox();
    const vp = page.viewportSize();
    const x = Math.min(panelBox.x + panelBox.width + 16, vp.width - 8);
    await page.mouse.click(x, vp.height / 2);
  } else if ((await page.locator(".ogis-info-panel").count()) > 0) {
    await page.locator("#attribution-button").click();
  } else {
    await page.locator("#menu-button").click();
  }
  await expect(page.locator(".ogis-panel")).not.toHaveClass(/show/);
};

/** Open a named tab in the side panel nav (desktop auto-opens the Info pane). */
const openPanelTab = async (page, roleOptions) => {
  if (!(await page.locator(".panel-nav").isVisible())) {
    await page.locator("#menu-button").click();
    await page.locator(".panel-nav").waitFor();
  }
  await page.locator(".panel-nav").getByRole("button", roleOptions).click();
  await expect(page.locator(".ogis-panel")).toHaveClass(/show/);
};

// ─── Core chrome states — one test per viewport, looping states ──────────────

for (const vp of VIEWPORTS) {
  test.describe(`matrix — ${vp.device} ${vp.orientation}`, () => {
    test.use({
      viewport: { width: vp.width, height: vp.height },
      hasTouch: vp.hasTouch,
    });

    test(`captures ${vp.device} ${vp.orientation} states @screenshots`, async ({
      page,
    }) => {
      const dir = `${OUT_ROOT}/${vp.device}/${vp.orientation}`;
      mkdirSync(dir, { recursive: true });

      trackConsoleErrors(page);
      await seedLocatePermission(page);
      await grantGeolocation(page);
      await page.goto(`/${BASE_HASH}`);
      await waitForMapIdle(page);
      await expect(page.locator("html")).toHaveAttribute(
        "data-bs-theme",
        "dark",
      );

      // closed — no panel. Desktop auto-opens the Info pane, so close it first.
      await closePanel(page);
      await page.waitForTimeout(350);
      await capture(page, dir, "closed");

      // menu-open — the tab strip (menu pane). Opened from a closed panel so
      // the menu button is always accessible, even on narrow screens.
      await page.locator("#menu-button").click();
      await expect(page.locator(".ogis-panel")).toHaveClass(/show/);
      await expect(page.locator(".panel-nav")).toBeVisible();
      await page.waitForTimeout(350);
      await capture(page, dir, "menu-open");

      // info-open — the Info pane, rendered without the tab strip. Close the
      // menu first (the panel covers the chip on narrow screens).
      await closePanel(page);
      await page.waitForTimeout(200);
      await page.locator("#attribution-button").click();
      await expect(page.locator(".ogis-info-panel")).toBeVisible();
      await expect(page.locator(".panel-nav")).toHaveCount(0);
      await page.waitForTimeout(350);
      await capture(page, dir, "info-open");

      // drag-collapsed — close the pane so the bottom-left chip is visible,
      // then drag the map to collapse the attribution chip.
      await closePanel(page);
      await page.waitForTimeout(350);
      await dragMap(page);
      // Collapse is signalled by the root data attribute; under SwiftShader the
      // drag→collapse transition can lag, so poll that real signal first, then
      // assert the text has been removed.
      await expect(page.locator(".ogis-root")).toHaveAttribute(
        "data-attrib-collapsed",
        "true",
        { timeout: 20000 },
      );
      await expect(
        page.locator("#attribution-button .ogis-attribution-chip__text"),
      ).toHaveCount(0, { timeout: 20000 });
      await page.waitForTimeout(150);
      await capture(page, dir, "drag-collapsed");

      // scale-collapsed — the MapLibre scale control sits inline beside the
      // collapsed chip (the root data attribute drives the CSS). Geometry is
      // asserted softly here: the matrix runs at every viewport.
      await expect(page.locator(".maplibregl-ctrl-scale")).toBeVisible();
      await capture(page, dir, "scale-collapsed");

      // locate-active — Locate chip becomes Located (permission pre-seeded).
      await page.locator("#locate-button").click();
      await expect(page.locator("#locate-button")).toContainText("Located", {
        timeout: 5000,
      });
      await waitForMapIdle(page);
      await capture(page, dir, "locate-active");

      // record-active — Record chip becomes Recording and opens the panel.
      await page.locator("#recordings-button").click();
      await expect
        .poll(() => page.locator("#recordings-button").textContent(), {
          timeout: 20000,
        })
        .toMatch(/Recording/);
      await page.waitForTimeout(350);
      await capture(page, dir, "record-active");
    });
  });
}

// ─── Feature states — desktop landscape, dark ────────────────────────────────
// Reach patterns mirror routes.spec.js, offline.spec.js and recordings.spec.js.

test.describe("Feature states — desktop landscape", () => {
  test.use({ viewport: { width: 1280, height: 720 } });

  test.beforeAll(() => {
    mkdirSync(FEATURE_DIR, { recursive: true });
  });

  test.beforeEach(async ({ page }) => {
    trackConsoleErrors(page);
  });

  test.afterEach(async ({ page }) => {
    expectNoConsoleErrors(page);
  });

  test("feature routes + navigation @screenshots", async ({ page }) => {
    await withGrantedStorage(page);
    await grantGeolocation(page);
    await page.goto(`/${BASE_HASH}`);
    await waitForMapIdle(page);

    await openPanelTab(page, { name: "Routes", exact: true });
    await page
      .locator('.ogis-panel input[type="file"]')
      .setInputFiles("tests/e2e/fixtures/route.gpx");
    await expect(
      page.locator(".ogis-panel").getByText("Test Loop"),
    ).toBeVisible();

    // Render the imported route on the map.
    await page
      .locator(".ogis-panel")
      .getByRole("button", { name: "Show", exact: true })
      .click();
    await waitForMapIdle(page);
    await capture(page, FEATURE_DIR, "feature-routes");

    // Start navigation — the panel reports the active navigation banner.
    await page
      .locator(".ogis-panel")
      .getByRole("button", { name: "Navigate", exact: true })
      .click();
    await expect(page.getByText(/Navigation active/)).toBeVisible();
    await page.waitForTimeout(500);
    await capture(page, FEATURE_DIR, "feature-route-navigating");
  });

  test("feature offline region @screenshots", async ({ page }) => {
    // Seed one downloaded region so the panel shows its list state.
    await page.addInitScript(() => {
      localStorage.setItem(
        "ogis_view_app",
        JSON.stringify({
          mapView: { center: { lat: 50.6539, lng: -128.0094 }, zoom: 14 },
        }),
      );
      localStorage.setItem(
        "ogis_offline-regions_app",
        JSON.stringify([
          {
            id: "test-region-1",
            name: "Test Region",
            createdAt: Date.now(),
            bounds: {
              west: -128.02,
              south: 50.64,
              east: -128.0,
              north: 50.66,
            },
            minZoom: 10,
            maxZoom: 11,
            tileCount: 12,
            estimatedBytes: 720000,
          },
        ]),
      );
    });

    await page.goto(`/${BASE_HASH}`);
    await waitForMapIdle(page);

    await openPanelTab(page, { name: /offline maps/i });
    await expect(
      page.locator(".ogis-panel").getByText("Test Region"),
    ).toBeVisible();
    await page.waitForTimeout(350);
    await capture(page, FEATURE_DIR, "feature-offline");
  });

  test("feature saved recording @screenshots", async ({ page }) => {
    // Seed one saved recording so the panel lists it with its actions.
    await page.addInitScript(() => {
      localStorage.setItem(
        "ogis_locate_app",
        JSON.stringify({ permissionGranted: true }),
      );
      localStorage.setItem(
        "ogis_view_app",
        JSON.stringify({
          mapView: { center: { lat: 50.6539, lng: -128.0094 }, zoom: 14 },
        }),
      );
      localStorage.setItem(
        "ogis_recordings_app",
        JSON.stringify({
          saved: [
            {
              id: "test-rec-1",
              timestamp: Date.now(),
              duration: 120000,
              distance: 500,
              points: [
                { lat: 50.6539, lng: -128.0094, t: Date.now() - 120000 },
                { lat: 50.655, lng: -128.008, t: Date.now() },
              ],
            },
          ],
          active: null,
        }),
      );
    });

    await page.goto(`/${BASE_HASH}`);
    await waitForMapIdle(page);

    await openPanelTab(page, { name: "Recordings", exact: true });
    await expect(
      page.locator(".ogis-panel").locator(".border-top"),
    ).toBeVisible();

    // Show the saved recording's track on the map.
    await page
      .locator(".ogis-panel")
      .getByRole("button", { name: "Show", exact: true })
      .click();
    await waitForMapIdle(page);
    await capture(page, FEATURE_DIR, "feature-recordings");
  });
});
