import { test, expect } from "../helpers/test.js";
import {
  trackConsoleErrors,
  expectNoConsoleErrors,
} from "../helpers/console.js";
import { renderBurst, waitForMapIdle } from "../helpers/mapIdle.js";
import {
  waitForLayoutSettled,
  normaliseCaptureState,
} from "../helpers/layout.js";
import { DEMO } from "../../fixtures/demo.mjs";
import { DEMO_AREA } from "../../fixtures/map/demoArea.mjs";
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { basename } from "node:path";

/**
 * UI-states screenshot matrix — `screenshots/{device}/{orientation}/*.jpg`
 *
 * Generates the committed visual-evidence matrix: every core chrome state at
 * six viewport combinations (phone/tablet/desktop × portrait/landscape), all in
 * the project-default dark theme, plus four feature states at the desktop
 * landscape viewport.
 *
 * These JPEGs are COMMITTED ARTEFACTS — the canonical visual evidence that
 * ships with the repository — generated by local full E2E runs (CI excludes
 * `@screenshots`; see `docs/13.ci.md`). Live map tiles make pixel comparisons brittle, so this
 * spec deliberately snapshots rather than compares (an explicit project
 * decision).
 *
 * Dark is the project default (`colorScheme: "dark"` in playwright.config.js).
 * Light mode is covered by the README hero spec and the settings spec.
 *
 * Every capture asserts zero console.error/pageerror. External Mapterhorn
 * raster 404s are filtered as expected network noise (see trackConsoleErrors).
 *
 * Layout note: widths ≥ 992 render the desktop layout (Bootstrap offcanvas
 * breakpoint). The desktop portrait window is a narrow 720 px, so it renders
 * the mobile layout; tablet landscape (1180) and desktop landscape (1280)
 * render the desktop layout.
 */

// SwiftShader software rendering starves the renderer: map-idle waits, drags
// and screenshots can each take tens of seconds, and a single test loops all
// seven states for one viewport. Under 4 concurrent workers a matrix test has
// been measured at >300 s, which truncated the final `record-active` state
// (the committed matrix came back with 41–44 of 46 files). 15 minutes leaves
// ample headroom for the full per-viewport loop at 4 workers.
test.setTimeout(900000);

// Local-only resilience for the whole file: under full-suite load a stalled
// live raster/TileJSON request can delay map-idle past the wait. All six matrix
// viewports and the feature-state tests inherit this retry. CI already applies
// global retries=2 and excludes `@screenshots` (`--grep-invert @screenshots`),
// so CI is unaffected.
test.describe.configure({ retries: 1 });

const OUT_ROOT = process.env.E2E_SCREENSHOTS_DIR || "screenshots";

// 3-segment hash is accepted and rewritten to 5 on load. Coordinates and zoom
// come from the demo-area single source of truth (`fixtures/map/demoArea.mjs`).
const DEMO_CENTER = DEMO_AREA.center;
const BASE_HASH = `#map=${DEMO_AREA.screenshotZoom}/${DEMO_CENTER.lat.toFixed(6)}/${DEMO_CENTER.lng.toFixed(6)}`;

// Feature states are captured at the desktop landscape viewport only.
const FEATURE_DIR = `${OUT_ROOT}/desktop/landscape`;

// Fixed epoch for every value the UI derives from `Date.now()` — seeded region
// and recording timestamps, and the live recording timer. Rendering wall-clock
// time makes captures drift between runs; pinning the source makes the rendered
// strings (and the 0:00 elapsed value) stable and reproducible.
const FIXED_TIMESTAMP = Date.parse("2024-01-01T00:00:00Z");
const RECORDING_CLOCK = new Date(FIXED_TIMESTAMP);

// device → orientation → viewport (width × height).
const VIEWPORTS = [
  {
    device: "phone",
    orientation: "portrait",
    width: 390,
    height: 844,
    hasTouch: true,
  },
  {
    device: "phone",
    orientation: "landscape",
    width: 844,
    height: 390,
    hasTouch: true,
  },
  {
    device: "tablet",
    orientation: "portrait",
    width: 820,
    height: 1180,
    hasTouch: true,
  },
  {
    device: "tablet",
    orientation: "landscape",
    width: 1180,
    height: 820,
    hasTouch: true,
  },
  {
    device: "desktop",
    orientation: "portrait",
    width: 720,
    height: 1280,
    hasTouch: false,
  },
  {
    device: "desktop",
    orientation: "landscape",
    width: 1280,
    height: 720,
    hasTouch: false,
  },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Collect a JSON-ready snapshot of the map state for capture diagnostics.
 *
 * The screenshot matrix must regenerate byte-identically; when a capture is
 * not reproducible the differing input has to be visible. This dump records
 * the camera, the loaded symbol data (label names via `querySourceFeatures`),
 * the tile cache and the map-fixture network timing, so two runs of the same
 * state can be diffed to locate the difference. Never throws: a diagnostics
 * failure must not fail the capture.
 */
const collectDiagnostics = async (page) => {
  try {
    return await page.evaluate(async () => {
      const mod = await import("/src/composables/useMap.js");
      const map = mod.getMapInstance("app");
      if (!map) return { error: "no map instance" };

      const style = map.getStyle();
      const layers = style.layers ?? [];

      const symbolPairs = [];
      const seenPairs = new Set();
      for (const layer of layers) {
        if (
          layer.type !== "symbol" ||
          !layer.source ||
          !layer["source-layer"]
        ) {
          continue;
        }
        const key = `${layer.source}\u0000${layer["source-layer"]}`;
        if (seenPairs.has(key)) continue;
        seenPairs.add(key);
        symbolPairs.push({
          source: layer.source,
          sourceLayer: layer["source-layer"],
        });
      }

      const labelFeatures = [];
      for (const { source, sourceLayer } of symbolPairs) {
        let features = [];
        try {
          features = map.querySourceFeatures(source, { sourceLayer });
        } catch {
          continue;
        }
        for (const feature of features) {
          const props = feature.properties ?? {};
          const name = props.name ?? props.name_en;
          if (!name) continue;
          labelFeatures.push({
            source,
            sourceLayer,
            name,
            geometryType: feature.geometry?.type ?? null,
            coordinates:
              feature.geometry?.type === "Point"
                ? feature.geometry.coordinates
                : null,
          });
        }
      }

      const tiles = {};
      for (const [sourceId, cache] of Object.entries(
        map.style.sourceCaches ?? {},
      )) {
        const cacheTiles = cache._tiles;
        if (!cacheTiles) continue;
        const values =
          cacheTiles instanceof Map || typeof cacheTiles.values === "function"
            ? [...cacheTiles.values()]
            : Object.values(cacheTiles);
        const entries = values
          .map((tile) => ({
            key: tile.tileID?.canonical?.key ?? tile.tileID?.key ?? null,
            state: tile.state ?? null,
            loaded: !!tile.loaded,
          }))
          .sort((a, b) => String(a.key).localeCompare(String(b.key)));
        tiles[sourceId] = entries;
      }

      const resources = performance
        .getEntriesByType("resource")
        .filter((entry) => /__e2e_map__|\/fonts\//.test(entry.name))
        .map((entry) => ({
          name: entry.name,
          transferSize: entry.transferSize,
          encodedBodySize: entry.encodedBodySize,
          responseStatus: entry.responseStatus ?? null,
        }));

      const canvas = map.getCanvas();
      const canvasRect = canvas.getBoundingClientRect();
      const scaleEl = document.querySelector(".maplibregl-ctrl-scale");
      const scaleRect = scaleEl ? scaleEl.getBoundingClientRect() : null;

      // Device/viewport state: a device-scale or viewport change re-rasterises
      // every glyph, so record it to full precision.
      const windowState = {
        innerWidth: window.innerWidth,
        innerHeight: window.innerHeight,
        outerWidth: window.outerWidth,
        outerHeight: window.outerHeight,
        devicePixelRatio: window.devicePixelRatio,
        visualViewport: window.visualViewport
          ? {
              width: window.visualViewport.width,
              height: window.visualViewport.height,
              scale: window.visualViewport.scale,
              offsetLeft: window.visualViewport.offsetLeft,
              offsetTop: window.visualViewport.offsetTop,
            }
          : null,
        screen: {
          width: window.screen.width,
          height: window.screen.height,
          availWidth: window.screen.availWidth,
          availHeight: window.screen.availHeight,
          colorDepth: window.screen.colorDepth,
          pixelDepth: window.screen.pixelDepth,
        },
      };

      // Full precision camera + the derived transform internals MapLibre uses
      // to place symbols. `getCenter()` round-trips through LngLat, but the
      // symbol projection is driven by `transform` — if any fractional field
      // differs, labels shift sub-pixel.
      const transform = map.transform;
      const transformSnapshot = {
        pixelRatio: transform.pixelRatio,
        tileSize: transform.tileSize,
        width: transform.width,
        height: transform.height,
        worldSize: transform.worldSize,
        zoom: transform.zoom,
        bearing: transform.bearing,
        pitch: transform.pitch,
        angle: transform.angle,
        elevation: transform.elevation,
        centerLng: transform.center ? transform.center.lng : null,
        centerLat: transform.center ? transform.center.lat : null,
        x: transform.x,
        y: transform.y,
        scale: transform.scale,
      };

      let contextAttributes = null;
      try {
        const gl = canvas.getContext("webgl2") || canvas.getContext("webgl");
        contextAttributes = gl ? gl.getContextAttributes() : null;
      } catch {
        // Context may be unavailable; leave null.
      }

      // Which glyph ranges are resident in the atlas, and whether any font
      // request has not completed (an in-flight glyph range can re-place
      // symbols after the capture point).
      let glyphRanges = null;
      try {
        const gm = map.style.glyphManager;
        if (gm && gm.entries instanceof Map) {
          glyphRanges = [...gm.entries.entries()]
            .map(([font, ranges]) => ({
              font,
              ranges: [...ranges.keys()].sort(),
            }))
            .sort((a, b) => a.font.localeCompare(b.font));
        }
      } catch {
        // Glyph manager internals are not stable API.
      }

      // Terrain: the active DEM source, its elevation, and which DEM tiles are
      // resident. A local DEM-tile change rescales the terrain mesh and shifts
      // draped symbols sub-pixel.
      let terrainState = null;
      try {
        const terrain =
          typeof map.getTerrain === "function" ? map.getTerrain() : map.terrain;
        if (terrain) {
          const cache = map.style.sourceCaches?.[terrain.source];
          const values = cache?._tiles
            ? cache._tiles instanceof Map
              ? [...cache._tiles.values()]
              : Object.values(cache._tiles)
            : [];
          const demTiles = values
            .map((tile) => ({
              key: tile.tileID?.canonical?.key ?? tile.tileID?.key ?? null,
              z: tile.tileID?.canonical?.z ?? null,
              state: tile.state ?? null,
              loaded: !!tile.loaded,
              hasTexture: !!tile.texture,
            }))
            .sort((a, b) => String(a.key).localeCompare(String(b.key)));
          terrainState = {
            source: terrain.source,
            exaggeration: terrain.exaggeration,
            transformElevation: transform.elevation,
            tiles: demTiles,
          };
        }
      } catch {
        // Terrain internals are not stable API.
      }

      let styleLoaded = null;
      try {
        styleLoaded = map.isStyleLoaded();
      } catch {
        // Style may be mid-swap.
      }

      // Requests for map assets that never completed (in flight at capture).
      let inFlight = [];
      try {
        inFlight = performance
          .getEntriesByType("resource")
          .filter((entry) => entry.responseEnd === 0 && entry.startTime > 0)
          .map((entry) => entry.name)
          .filter((name) => /__e2e_map__|\/fonts\/|\/sprite/.test(name));
      } catch {
        // Resource timing may be unavailable.
      }

      // Fade/opacity state: a symbol drawn with a fractional opacity is a fade
      // that has not settled. Packed opacities are 0 or 1 when settled; any
      // value strictly between identifies a mid-fade symbol.
      const fractionalOpacities = [];
      let fade = null;
      try {
        const placement = map.style?.placement;
        fade = {
          mapFadeDuration: map._fadeDuration,
          idleTriggered: map._idleTriggered,
          placementFadeDuration: placement?.fadeDuration ?? null,
          painterFadeDuration: map.painter?.options?.fadeDuration ?? null,
          symbolFadeChange: map.painter?.symbolFadeChange ?? null,
        };
        const opacities = placement?.opacities;
        if (opacities) {
          for (const [crossTileID, state] of Object.entries(opacities)) {
            for (const kind of ["text", "icon"]) {
              const o = state[kind];
              if (o && o.opacity !== 0 && o.opacity !== 1) {
                fractionalOpacities.push({
                  crossTileID,
                  kind,
                  opacity: o.opacity,
                  placed: o.placed,
                });
              }
            }
          }
        }
      } catch {
        // Placement internals are not stable API.
      }

      return {
        camera: {
          center: map.getCenter(),
          zoom: map.getZoom(),
          bearing: map.getBearing(),
          pitch: map.getPitch(),
        },
        transform: transformSnapshot,
        fade,
        fractionalOpacities,
        window: windowState,
        performanceNow: performance.now(),
        fonts: document.fonts
          ? { status: document.fonts.status, size: document.fonts.size }
          : null,
        canvas: {
          width: canvas.width,
          height: canvas.height,
          clientWidth: canvas.clientWidth,
          clientHeight: canvas.clientHeight,
          contextAttributes,
          rect: {
            x: canvasRect.x,
            y: canvasRect.y,
            width: canvasRect.width,
            height: canvasRect.height,
            top: canvasRect.top,
            right: canvasRect.right,
            bottom: canvasRect.bottom,
            left: canvasRect.left,
          },
        },
        scale: scaleRect
          ? {
              textContent: scaleEl.textContent,
              x: scaleRect.x,
              y: scaleRect.y,
              width: scaleRect.width,
              height: scaleRect.height,
              top: scaleRect.top,
              right: scaleRect.right,
              bottom: scaleRect.bottom,
              left: scaleRect.left,
              offsetWidth: scaleEl.offsetWidth,
              offsetHeight: scaleEl.offsetHeight,
              clientWidth: scaleEl.clientWidth,
              clientHeight: scaleEl.clientHeight,
              styleWidth: scaleEl.style.width,
            }
          : null,
        sources: Object.keys(style.sources ?? {}),
        symbolPairs,
        labelFeatures,
        tiles,
        terrain: terrainState,
        glyphRanges,
        resources,
        inFlight,
        flags: {
          loaded: map.loaded(),
          tilesLoaded: map.areTilesLoaded(),
          moving: map.isMoving(),
          styleLoaded,
          placementDirty: !!map.style._placementDirty,
          styleChanged: !!map.style._changed,
        },
      };
    });
  } catch (error) {
    return { error: String(error) };
  }
};

/**
 * Toggle a full-viewport probe overlay so a screenshot can prove the renderer
 * is live. Under heavy load the surface can lag the DOM by seconds; the probe
 * must force renderer-side content (a fresh full-viewport layer to raster),
 * not just a compositor-side property change — a stalled renderer can still
 * let the compositor redraw existing tiles with a CSS filter. A frame that
 * contains the overlay is newer than the toggle — and therefore also contains
 * every earlier DOM change (e.g. an opened panel or a chip's new label).
 */
const setCaptureProbe = async (page, visible) => {
  await page.evaluate((on) => {
    let probe = document.getElementById("__capture_probe__");
    if (!probe) {
      probe = document.createElement("div");
      probe.id = "__capture_probe__";
      probe.style.cssText =
        "position:fixed;inset:0;pointer-events:none;z-index:2147483647;background:rgba(255,0,255,0.08)";
      document.documentElement.appendChild(probe);
    }
    probe.style.display = on ? "block" : "none";
  }, visible);
  // Let the renderer run a frame before the screenshot reads the surface.
  await page.evaluate(
    () =>
      new Promise((resolve) =>
        requestAnimationFrame(() => requestAnimationFrame(resolve)),
      ),
  );
};

/**
 * Screenshot one state once the composited output has stopped changing.
 *
 * The map can end a settle with a placement change that never scheduled a
 * render (`Style._updatePlacement` reports "no change" once a committed
 * placement has no transitions left), so a passive screenshot loop can read a
 * frame from before that placement — e.g. one whose labels are not yet drawn.
 * Each round therefore drives a render burst, then proves the compositor is
 * live: under heavy load the surface can lag the DOM by seconds, and an
 * equality-only loop will happily accept a stale (older, coherent) state. A
 * temporary full-viewport overlay must change the captured frame; if it does
 * not, the surface is stale and the probe retries. The shot is accepted only
 * when two consecutive fresh frames are byte-identical. Bounded so a genuinely
 * animated element cannot hang the run. Console errors are asserted once
 * settled. After the write, a diagnostics snapshot is recorded under
 * `${E2E_SCREENSHOTS_DIR}/diag/<run>/` for run-to-run diffs — opt-in via that
 * env var; committed in-place runs (no env var) write nothing.
 */
const capture = async (page, dir, name) => {
  const options = { type: "jpeg", quality: 80 };
  const MAX_ROUNDS = 12;
  const MAX_PROBES = 10;
  let previous = null;
  let buffer = null;
  for (let round = 0; round < MAX_ROUNDS; round++) {
    await renderBurst(page, 300);
    // Let the compositor present the frame the burst just rendered.
    await page.waitForTimeout(250);
    // Freshness gate: a live compositor must reflect a full-viewport change.
    let fresh = null;
    for (let probe = 0; probe < MAX_PROBES; probe++) {
      await setCaptureProbe(page, true);
      const probed = await page.screenshot(options);
      await setCaptureProbe(page, false);
      const clear = await page.screenshot(options);
      if (!probed.equals(clear)) {
        fresh = clear;
        break;
      }
      await page.waitForTimeout(250);
    }
    if (fresh === null) {
      throw new Error(
        `capture(${name}): the compositor never reflected a forced repaint`,
      );
    }
    buffer = fresh;
    if (previous !== null && previous.equals(buffer)) break;
    previous = buffer;
  }
  writeFileSync(`${dir}/${name}.jpg`, buffer);
  expectNoConsoleErrors(page);

  if (process.env.E2E_SCREENSHOTS_DIR) {
    try {
      const diagDir = `${process.env.E2E_SCREENSHOTS_DIR}/diag/${basename(OUT_ROOT)}`;
      mkdirSync(diagDir, { recursive: true });
      const diagName = `${dir
        .replace(`${OUT_ROOT}/`, "")
        .replaceAll("/", "-")}-${name}.json`;
      // Lossless evidence is expensive under SwiftShader, so record it only for
      // the feature state that has shown run-to-run variance. The JSON
      // snapshot above is cheap and is still recorded for every capture.
      const lossless = name === "feature-offline";
      if (lossless) {
        // The composited frame (no JPEG quantisation) and the raw map canvas.
        // Two JPEG variants can differ only through JPEG quantisation; these
        // PNGs show whether the underlying render itself differs.
        try {
          const png = await page.screenshot({ type: "png" });
          writeFileSync(`${diagDir}/${diagName}.png`, png);
          const canvasPng = await page
            .locator(".ogis-map canvas")
            .screenshot({ type: "png" });
          writeFileSync(`${diagDir}/${diagName}.canvas.png`, canvasPng);
        } catch {
          // Lossless evidence is optional.
        }
      }
      // Time-series evidence: is the accepted frame already a stable fixed
      // point, or is the map still drifting? Capture the raw canvas three times
      // with a render burst between, and record the lossless hashes. If they
      // stop changing immediately the accepted state is converged; if the first
      // hashes differ from later ones, capture accepted a transient frame.
      let canvasStability = null;
      if (lossless) {
        try {
          const hashes = [];
          for (let i = 0; i < 3; i++) {
            const shot = await page
              .locator(".ogis-map canvas")
              .screenshot({ type: "png" });
            hashes.push(createHash("sha256").update(shot).digest("hex"));
            await renderBurst(page, 300);
            await page.waitForTimeout(250);
          }
          canvasStability = hashes;
        } catch {
          // Stability probe is optional.
        }
      }
      const diag = await collectDiagnostics(page);
      writeFileSync(
        `${diagDir}/${diagName}`,
        JSON.stringify(
          {
            sha256: createHash("sha256").update(buffer).digest("hex"),
            canvasStability,
            diag,
          },
          null,
          2,
        ),
      );
    } catch {
      // Diagnostics must never fail a capture.
    }
  }
};

/**
 * Pin the auto-assigned line colour for capture.
 *
 * `useGeoJSON` picks a random bright palette colour for any feature that
 * declares no `ogis.color` — and the route feature deliberately declares only
 * width/opacity (`src/features/routes/index.js`). A seeded `Math.random` cannot
 * make that choice reproducible: MapLibre draws a worker message id from
 * `Math.random()` (its `sendAsync`), so the PRNG advances a timing-dependent
 * number of times before the route is imported. Across sessions the route line
 * therefore rendered orange in one run and green in the next — a whole-map
 * colour diff. Setting the line default through the composable's public API
 * before the import fixes the colour.
 */
const pinLineColor = (page) =>
  page.evaluate(async () => {
    const mod = await import("/src/composables/useGeoJSON.js");
    mod.useGeoJSON("app").setDefaults({ line: { color: "#e74c3c" } });
  });

/**
 * Stabilise the GPU-composited "glass" surfaces for capture.
 *
 * The corner-control chips and the Info panel footer use
 * `backdrop-filter: blur(...)`, and the chips also carry
 * `box-shadow: 0 1px 6px ...`. Chromium composites both on separate GPU layers
 * whose blur sampling and antialiased pill edges vary subtly between browser
 * launches — leaving sub-percent pixel drift in the committed JPEGs (measured:
 * ~0.9 % of pixels, max Δ71 on the attribution chip) under a full 4-worker run
 * even though the underlying page (including the map canvas) is byte identical.
 * Dropping the backdrop filter and box shadow removes the nondeterministic
 * layers; the chips keep their background fill, border and text, so the result
 * is visually all but identical while the raster becomes reproducible. This is
 * a deliberate capture-only tradeoff; production rendering is untouched.
 */
const stabilizeCaptureRendering = (page) =>
  page.addStyleTag({
    content:
      "*,*::before,*::after{backdrop-filter:none!important;-webkit-backdrop-filter:none!important;box-shadow:none!important;}",
  });

/**
 * Seed `Math.random` with a fixed PRNG before the app boots.
 *
 * `useGeoJSON` auto-assigns a colour from a bright palette when a feature
 * declares none, so the imported GPX route line changes colour every run.
 * `importGPX` also derives its route id from `Math.random`. A deterministic
 * sequence makes both reproducible; nothing in the app depends on randomness
 * for correctness.
 */
const seedDeterministicRandom = (page) =>
  page.addInitScript(() => {
    let state = 0x9e3779b9;
    Math.random = () => {
      state = (state + 0x6d2b79f5) | 0;
      let t = Math.imul(state ^ (state >>> 15), 1 | state);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  });

/**
 * Seed only the locate permission — the view storage is deliberately left
 * absent so the capture starts from the app's default view. This lets one page
 * load cover the locate/record states without a mid-test reload.
 */
const seedLocatePermission = (page) =>
  page.addInitScript(() => {
    localStorage.setItem(
      "ogis_locate_app",
      JSON.stringify({ permissionGranted: true }),
    );
  });

/** Seed permission + a known view storage. */
const withGrantedStorage = (page) =>
  page.addInitScript((center) => {
    localStorage.setItem(
      "ogis_locate_app",
      JSON.stringify({ permissionGranted: true }),
    );
    localStorage.setItem(
      "ogis_view_app",
      JSON.stringify({
        mapView: { center, zoom: 14 },
      }),
    );
  }, DEMO_CENTER);

/**
 * Grant geolocation permission and fix the position at the demo centre.
 *
 * The locate click flies to this position at zoom 16 — the same centre and
 * zoom as the capture view — so the camera never moves during locate-active
 * and no re-placement race can leave a labels-less frame.
 */
const grantGeolocation = (page) => {
  const { lat, lng } = DEMO.center;
  return page
    .context()
    .grantPermissions(["geolocation"])
    .then(() =>
      page.context().setGeolocation({ latitude: lat, longitude: lng }),
    );
};

/**
 * Rebase the demo slice onto the pinned capture clock.
 *
 * Fixture timestamps are unix SECONDS; seeded recording points need the app's
 * `{lat, lng, t}` epoch-MILLISECONDS shape, with the last point landing at
 * `RECORDING_CLOCK` so the crafted ride shares the pinned clock.
 */
const rebaseSlice = () => {
  const lastT = DEMO.slice.at(-1).t;
  return DEMO.slice.map((point) => ({
    lat: point.lat,
    lng: point.lng,
    t: RECORDING_CLOCK.getTime() - (lastT - point.t) * 1000,
  }));
};

/**
 * Seed a paused in-progress recording so the feature's crash recovery draws
 * the crafted ride at load, alongside a "Paused" chip.
 */
const seedPausedRecording = (page) =>
  page.addInitScript(
    ({ points, startTime }) => {
      localStorage.setItem(
        "ogis_recordings_app",
        JSON.stringify({ saved: [], active: { points, startTime } }),
      );
    },
    {
      points: rebaseSlice(),
      startTime: RECORDING_CLOCK.getTime() - DEMO.sliceDuration * 1000,
    },
  );

/**
 * Mouse-drag the map canvas horizontally to collapse the attribution chip.
 *
 * The pointer is held still before release so MapLibre's drag-inertia velocity
 * decays to zero. Without it, the fling distance depends on how fast the
 * synthetic move events land, leaving the map's final centre (and therefore
 * every subsequent capture) slightly different run to run.
 */
const dragMap = async (page, dx = 200) => {
  const canvas = page.locator(".ogis-map canvas");
  await canvas.waitFor({ state: "visible" });
  const box = await canvas.boundingBox();
  const x = box.x + box.width / 2;
  const y = box.y + box.height / 2;
  // Keep the release point on-screen: a pointerup outside the viewport is not
  // delivered, so MapLibre never fires dragend/moveend and the map-idle signal
  // is never restored.
  const endX = Math.min(x + dx, box.x + box.width - 24);
  await page.mouse.move(x, y);
  await page.mouse.down();
  await page.mouse.move(endX, y, { steps: 10 });
  await page.waitForTimeout(250);
  await page.mouse.up();
};

/** True when the side panel currently has the Bootstrap `show` class. */
const isPanelShown = (page) =>
  page
    .locator(".ogis-panel.show")
    .count()
    .then((n) => n > 0);

/**
 * Close any open pane. On narrow screens the panel is capped narrower than the
 * viewport, leaving a strip of dismiss backdrop beside it; wait for the
 * slide-in transition to settle, then click that strip with a real pointer
 * event. On desktop there is no backdrop and the panel leaves the controls
 * accessible, so the chip/menu buttons toggle their panes closed.
 */
const closePanel = async (page) => {
  if (!(await isPanelShown(page))) return;
  const backdrop = page.locator(".offcanvas-backdrop");
  if (await backdrop.count()) {
    // The panel no longer covers the backdrop, so a real pointer click on the
    // visible strip reaches the backdrop's Vue close handler. Wait for the
    // offcanvas transform transition first — a mid-slide bounding box would
    // move the click target under the panel.
    await page.waitForFunction(() => {
      const panel = document.querySelector(".ogis-panel");
      return panel && getComputedStyle(panel).transform === "none";
    });
    const panelBox = await page.locator(".ogis-panel").boundingBox();
    const vp = page.viewportSize();
    const x = Math.min(panelBox.x + panelBox.width + 16, vp.width - 8);
    await page.mouse.click(x, vp.height / 2);
  } else if ((await page.locator(".ogis-info-panel").count()) > 0) {
    await page.locator("#attribution-button").click();
  } else {
    await page.locator("#menu-button").click();
  }
  await expect(page.locator(".ogis-panel")).not.toHaveClass(/show/);
};

/** Open a named tab in the side panel nav (desktop auto-opens the Info pane). */
const openPanelTab = async (page, roleOptions) => {
  if (!(await page.locator(".panel-nav").isVisible())) {
    await page.locator("#menu-button").click();
    await page.locator(".panel-nav").waitFor();
  }
  await page.locator(".panel-nav").getByRole("button", roleOptions).click();
  await expect(page.locator(".ogis-panel")).toHaveClass(/show/);
};

// ─── Core chrome states — one test per viewport, looping states ──────────────

for (const vp of VIEWPORTS) {
  test.describe(`matrix — ${vp.device} ${vp.orientation}`, () => {
    test.use({
      viewport: { width: vp.width, height: vp.height },
      hasTouch: vp.hasTouch,
    });

    test(`captures ${vp.device} ${vp.orientation} states @screenshots`, async ({
      page,
    }, testInfo) => {
      const dir = `${OUT_ROOT}/${vp.device}/${vp.orientation}`;
      mkdirSync(dir, { recursive: true });

      trackConsoleErrors(page);
      await seedDeterministicRandom(page);
      await seedLocatePermission(page);
      await grantGeolocation(page);
      await page.goto(`/${BASE_HASH}`);
      await stabilizeCaptureRendering(page);
      await waitForMapIdle(page, testInfo);
      await expect(page.locator("html")).toHaveAttribute(
        "data-bs-theme",
        "dark",
      );

      // closed — no panel. Desktop auto-opens the Info pane, so close it first.
      await closePanel(page);
      await normaliseCaptureState(page, testInfo);
      await capture(page, dir, "closed");

      // menu-open — the tab strip (menu pane). Opened from a closed panel so
      // the menu button is always accessible, even on narrow screens.
      await page.locator("#menu-button").click();
      await expect(page.locator(".ogis-panel")).toHaveClass(/show/);
      await expect(page.locator(".panel-nav")).toBeVisible();
      await normaliseCaptureState(page, testInfo);
      await capture(page, dir, "menu-open");

      // info-open — the Info pane, rendered without the tab strip. Close the
      // menu first (the panel covers the chip on narrow screens).
      await closePanel(page);
      await waitForLayoutSettled(page, testInfo);
      await page.locator("#attribution-button").click();
      await expect(page.locator(".ogis-info-panel")).toBeVisible();
      await expect(page.locator(".panel-nav")).toHaveCount(0);
      await normaliseCaptureState(page, testInfo);
      await capture(page, dir, "info-open");

      // drag-collapsed — close the pane so the bottom-left chip is visible,
      // then drag the map to collapse the attribution chip.
      await closePanel(page);
      await waitForLayoutSettled(page, testInfo);
      await dragMap(page);
      // Collapse is signalled by the root data attribute; under SwiftShader the
      // drag→collapse transition can lag, so poll that real signal first, then
      // assert the text has been removed.
      await expect(page.locator(".ogis-root")).toHaveAttribute(
        "data-attrib-collapsed",
        "true",
        { timeout: 20000 },
      );
      await expect(
        page.locator("#attribution-button .ogis-attribution-chip__text"),
      ).toHaveCount(0, { timeout: 20000 });
      await normaliseCaptureState(page, testInfo);
      await capture(page, dir, "drag-collapsed");

      // scale-collapsed — the MapLibre scale control sits inline beside the
      // collapsed chip (the root data attribute drives the CSS). Geometry is
      // asserted softly here: the matrix runs at every viewport.
      await expect(page.locator(".maplibregl-ctrl-scale")).toBeVisible();
      await normaliseCaptureState(page, testInfo);
      await capture(page, dir, "scale-collapsed");

      // locate-active — Locate chip becomes Located (permission pre-seeded).
      await page.locator("#locate-button").click();
      await expect(page.locator("#locate-button")).toContainText("Located", {
        timeout: 5000,
      });
      await normaliseCaptureState(page, testInfo);
      await capture(page, dir, "locate-active");

      // record-active — a paused in-progress ride is seeded and reloaded so the
      // Record chip starts as "Paused". Pin Date.now() before resuming: the live
      // elapsed timer keeps ticking via setInterval, but with the clock fixed
      // the panel renders a stable elapsed time derived from the seeded
      // startTime. The chip click takes the resume path (the app does not open
      // the panel on resume), so open the panel deliberately.
      await seedPausedRecording(page);
      await page.reload();
      await stabilizeCaptureRendering(page);
      await waitForMapIdle(page, testInfo);
      await page.clock.setFixedTime(RECORDING_CLOCK);
      // Resuming pushes the current position as the ride's next point; stubbing
      // the slice end duplicates the track's last point (no spur from the
      // centre stub used by the locate state).
      const sliceEnd = DEMO.slice.at(-1);
      await page.context().setGeolocation({
        latitude: sliceEnd.lat,
        longitude: sliceEnd.lng,
      });
      await page.locator("#recordings-button").click();
      await expect
        .poll(() => page.locator("#recordings-button").textContent(), {
          timeout: 20000,
        })
        .toMatch(/Recording/);
      await openPanelTab(page, { name: "Recordings", exact: true });
      await normaliseCaptureState(page, testInfo);
      await capture(page, dir, "record-active");
    });
  });
}

// ─── Feature states — desktop landscape, dark ────────────────────────────────
// Reach patterns mirror routes.spec.js, offline.spec.js and recordings.spec.js.

test.describe("Feature states — desktop landscape", () => {
  test.use({ viewport: { width: 1280, height: 720 } });

  test.beforeAll(() => {
    mkdirSync(FEATURE_DIR, { recursive: true });
  });

  test.beforeEach(async ({ page }) => {
    trackConsoleErrors(page);
    await seedDeterministicRandom(page);
  });

  test.afterEach(async ({ page }) => {
    expectNoConsoleErrors(page);
  });

  test("feature routes + navigation @screenshots", async ({
    page,
  }, testInfo) => {
    await withGrantedStorage(page);
    await grantGeolocation(page);
    await page.goto(`/${BASE_HASH}`);
    await stabilizeCaptureRendering(page);
    await waitForMapIdle(page, testInfo);

    await openPanelTab(page, { name: "Routes", exact: true });
    // The panel resize changes the map container width; `showOnMap` fits bounds
    // to that container, so wait for the resize before the fit runs.
    await waitForLayoutSettled(page, testInfo);
    await pinLineColor(page);
    await page
      .locator('.ogis-panel input[type="file"]')
      .setInputFiles("tests/fixtures/route.gpx");
    await expect(
      page.locator(".ogis-panel").getByText("Test Loop"),
    ).toBeVisible();

    // Render the imported route on the map.
    await page
      .locator(".ogis-panel")
      .getByRole("button", { name: "Show", exact: true })
      .click();
    await normaliseCaptureState(page, testInfo);
    await capture(page, FEATURE_DIR, "feature-routes");

    // Start navigation — the panel reports the active navigation banner.
    await page
      .locator(".ogis-panel")
      .getByRole("button", { name: "Navigate", exact: true })
      .click();
    await expect(page.getByText(/Navigation active/)).toBeVisible();
    await normaliseCaptureState(page, testInfo);
    await capture(page, FEATURE_DIR, "feature-route-navigating");
  });

  test("feature offline region @screenshots", async ({ page }, testInfo) => {
    // Seed one downloaded region so the panel shows its list state. The
    // displayed `createdAt` is pinned so the rendered date never drifts.
    await page.addInitScript(
      ({ center, fixedTimestamp, bounds }) => {
        // The panel's storage summary reads the live Storage API, whose usage
        // grows as the profile's caches change between runs. Pin both values so
        // the rendered "x of y used" text and bar are stable.
        if (navigator.storage) {
          Object.defineProperty(navigator.storage, "estimate", {
            configurable: true,
            value: async () => ({ usage: 1048576, quota: 1073741824 }),
          });
          Object.defineProperty(navigator.storage, "persisted", {
            configurable: true,
            value: async () => true,
          });
        }
        localStorage.setItem(
          "ogis_view_app",
          JSON.stringify({
            mapView: { center, zoom: 14 },
          }),
        );
        localStorage.setItem(
          "ogis_offline-regions_app",
          JSON.stringify([
            {
              id: "test-region-1",
              name: "Test Region",
              createdAt: fixedTimestamp,
              bounds,
              minZoom: 10,
              maxZoom: 11,
              tileCount: 12,
              estimatedBytes: 720000,
            },
          ]),
        );
      },
      {
        center: DEMO_CENTER,
        fixedTimestamp: FIXED_TIMESTAMP,
        bounds: DEMO.offlineRegion,
      },
    );

    await page.goto(`/${BASE_HASH}`);
    await stabilizeCaptureRendering(page);
    await waitForMapIdle(page, testInfo);

    await openPanelTab(page, { name: /offline maps/i });
    await waitForLayoutSettled(page, testInfo);
    await expect(
      page.locator(".ogis-panel").getByText("Test Region"),
    ).toBeVisible();
    // The demo food POI sits on the terrain surface, so the terrain
    // depth-visibility factor can land on either side of the "in front" test
    // depending on when the depth framebuffer was last drawn; the shared
    // normalisation pins it, as it does for every other capture.
    await normaliseCaptureState(page, testInfo);
    await capture(page, FEATURE_DIR, "feature-offline");
  });

  test("feature saved recording @screenshots", async ({ page }, testInfo) => {
    // Seed one saved recording so the panel lists it with its actions. The
    // displayed timestamp is pinned so the rendered date never drifts.
    await page.addInitScript(
      ({ center, recording }) => {
        localStorage.setItem(
          "ogis_locate_app",
          JSON.stringify({ permissionGranted: true }),
        );
        localStorage.setItem(
          "ogis_view_app",
          JSON.stringify({
            mapView: { center, zoom: 14 },
          }),
        );
        localStorage.setItem(
          "ogis_recordings_app",
          JSON.stringify({ saved: [recording], active: null }),
        );
      },
      {
        center: DEMO_CENTER,
        recording: {
          id: "test-rec-1",
          timestamp: RECORDING_CLOCK.getTime() - DEMO.sliceDuration * 1000,
          duration: DEMO.sliceDuration * 1000,
          distance: DEMO.sliceDistance,
          points: rebaseSlice(),
        },
      },
    );

    await page.goto(`/${BASE_HASH}`);
    await stabilizeCaptureRendering(page);
    await waitForMapIdle(page, testInfo);

    await openPanelTab(page, { name: "Recordings", exact: true });
    await waitForLayoutSettled(page, testInfo);
    await expect(
      page.locator(".ogis-panel").locator(".border-top"),
    ).toBeVisible();

    // Show the saved recording's track on the map.
    await page
      .locator(".ogis-panel")
      .getByRole("button", { name: "Show", exact: true })
      .click();
    await normaliseCaptureState(page, testInfo);
    await capture(page, FEATURE_DIR, "feature-recordings");
  });
});
